// 
// Shell_cfg.h
//
// configuration parameters for the game shell


// Text colors
int TEXT_COLOR_MAIN_R = 255;
int TEXT_COLOR_MAIN_G = 0;
int TEXT_COLOR_MAIN_B = 70;

// Font name, size, etc
#define BUTTON_TEXT_NAME "Star Next"
#define BUTTON_TEXT_SIZE 10

// Main Menu Button positions
int BTN_MAIN_SINGLE_X = 460;
int BTN_MAIN_SINGLE_Y = 267;
int BTN_MAIN_MULTI_X = 460;
int BTN_MAIN_MULTI_Y = 300;
int BTN_MAIN_REPLAY_X = 460;
int BTN_MAIN_REPLAY_Y = 333;
int BTN_MAIN_CREDITS_X = 460;
int BTN_MAIN_CREDITS_Y = 366;
int BTN_MAIN_OPTIONS_X = 460;
int BTN_MAIN_OPTIONS_Y = 399;
int BTN_MAIN_QUIT_X = 460;
int BTN_MAIN_QUIT_Y = 432;
int BTN_MAIN_WIDTH = 180;
int BTN_MAIN_HEIGHT = 25;
int MOVIE_MAIN_X = 120;
int MOVIE_MAIN_Y = 40;
int MOVIE_MAIN_WIDTH = 320;
int MOVIE_MAIN_HEIGHT = 240;



// Single Player Menu Buttons
int BTN_SINGLE_TRAIN_X = 460;
int BTN_SINGLE_TRAIN_Y = 333;
int BTN_SINGLE_LOAD_X = 460;
int BTN_SINGLE_LOAD_Y = 366;
int BTN_SINGLE_OPTIONS_X = 460;
int BTN_SINGLE_OPTIONS_Y = 399;
int BTN_SINGLE_BACK_X = 460;
int BTN_SINGLE_BACK_Y = 432;
int BTN_SINGLE_FG_X = 130;
int BTN_SINGLE_FG_Y = 40;
int BTN_SINGLE_FG_W = 111;
int BTN_SINGLE_FG_H = 101;
int BTN_SINGLE_IM_X = 90;
int BTN_SINGLE_IM_Y = 220;
int BTN_SINGLE_IM_W = 108;
int BTN_SINGLE_IM_H = 98;


// Mission Briefing Menu Buttons
int BTN_MBRIEF_LAUNCH_X = 460;
int BTN_MBRIEF_LAUNCH_Y = 300;
int BTN_MBRIEF_MAIN_MENU_X = 460;
int BTN_MBRIEF_MAIN_MENU_Y = 333;
int BTN_MBRIEF_OPTIONS_X = 460;
int BTN_MBRIEF_OPTIONS_Y = 366;
int BTN_MBRIEF_ARCHIVE_X = 460;
int BTN_MBRIEF_ARCHIVE_Y = 399;
int BTN_MBRIEF_BACK_X = 460;
int BTN_MBRIEF_BACK_Y = 432;
int BTN_MBRIEF_BRIEF_X = 10;
int BTN_MBRIEF_BRIEF_Y = 10;
int BTN_MBRIEF_BRIEF_W = 200;
int BTN_MBRIEF_BRIEF_H = 470;
int BTN_MBRIEF_LIST_X = 250;
int BTN_MBRIEF_LIST_Y = 10;
int BTN_MBRIEF_LIST_W = 200;
int BTN_MBRIEF_LIST_H = 150;


// Options Menu Button positions
int BTN_OPTIONS_PLAY_X = 460;
int BTN_OPTIONS_PLAY_Y = 300;
int BTN_OPTIONS_GRAPHICS_X = 460;
int BTN_OPTIONS_GRAPHICS_Y = 333;
int BTN_OPTIONS_AUDIO_X = 460;
int BTN_OPTIONS_AUDIO_Y = 366;
int BTN_OPTIONS_INPUT_X = 460;
int BTN_OPTIONS_INPUT_Y = 399;
int BTN_OPTIONS_BACK_X = 460;
int BTN_OPTIONS_BACK_Y = 432;


// Escape Options Menu Button positions
int BTN_ESC_RETURN_X = 460;
int BTN_ESC_RETURN_Y = 267;
int BTN_ESC_SAVE_X = 460;
int BTN_ESC_SAVE_Y = 300;
int BTN_ESC_LOAD_X = 460;
int BTN_ESC_LOAD_Y = 333;
int BTN_ESC_RESTART_X = 460;
int BTN_ESC_RESTART_Y = 366;
int BTN_ESC_OPTIONS_X = 460;
int BTN_ESC_OPTIONS_Y = 399;
int BTN_ESC_ABORT_X = 460;
int BTN_ESC_ABORT_Y = 432;





